"""Add redularity, total_price to orders

Revision ID: 01ae06addb1b
Revises: c469e0fa183d
Create Date: 2026-04-06 19:39:01.014275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01ae06addb1b'
down_revision: Union[str, Sequence[str], None] = 'c469e0fa183d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('regularity', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'total_price')
    op.drop_column('orders', 'regularity')
    # ### end Alembic commands ###
