"""add team_id to payments

Revision ID: 981ae0934001
Revises: 9f2919ae1477
Create Date: 2026-04-14 20:33:44.142981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '981ae0934001'
down_revision: Union[str, Sequence[str], None] = '9f2919ae1477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payments', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'team_id')
    # ### end Alembic commands ###
