"""delete desc+plant_type from plants and add name

Revision ID: 9f2919ae1477
Revises: 427fadcd2bee
Create Date: 2026-04-11 18:58:59.420908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f2919ae1477'
down_revision: Union[str, Sequence[str], None] = '427fadcd2bee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('plants', 'description')
    op.drop_column('plants', 'plant_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('plant_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('plants', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('plants', 'name')
    # ### end Alembic commands ###
