"""undo replace image_url to image

Revision ID: b93d3351ed3d
Revises: f3d9ca043ebf
Create Date: 2026-04-07 08:00:44.209297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b93d3351ed3d'
down_revision: Union[str, Sequence[str], None] = 'f3d9ca043ebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('image_url', sa.String(), nullable=True))
    op.drop_column('services', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('image', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('services', 'image_url')
    # ### end Alembic commands ###
