"""Add execution_date to orders

Revision ID: c469e0fa183d
Revises: 65cb8aa1c25e
Create Date: 2026-04-06 19:34:01.214363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c469e0fa183d'
down_revision: Union[str, Sequence[str], None] = '65cb8aa1c25e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('execution_date', sa.DateTime(), nullable=True))
    op.create_foreign_key('fk_teams_users', 'teams', 'users', ['leader_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_users_teams', 'users', 'teams', ['team_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_teams', 'users', type_='foreignkey')
    op.drop_constraint('fk_teams_users', 'teams', type_='foreignkey')
    op.drop_column('orders', 'execution_date')
    # ### end Alembic commands ###
