"""make team_id not nullable in payments

Revision ID: e92f65191e03
Revises: 981ae0934001
Create Date: 2026-04-14 20:35:09.127241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e92f65191e03'
down_revision: Union[str, Sequence[str], None] = '981ae0934001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Fill team_id for existing payments
    op.execute("""
    UPDATE payments 
    SET team_id = orders.team_id 
    FROM orders 
    WHERE payments.order_id = orders.id AND payments.team_id IS NULL
    """)
    op.alter_column('payments', 'team_id', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'team_id', nullable=True)
    # ### end Alembic commands ###
