"""replace image_url to image

Revision ID: f3d9ca043ebf
Revises: 0884b37aef39
Create Date: 2026-04-06 21:50:35.090511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d9ca043ebf'
down_revision: Union[str, Sequence[str], None] = '0884b37aef39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('image', sa.LargeBinary(), nullable=True))
    op.drop_column('services', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('services', 'image')
    # ### end Alembic commands ###
